### ISSUE TITLE
Game runs at 20sec/tick speed after creating user

### ISSUE THREAD

**Issue by Ondalf** [ags131/screeps-local#3]
`Rooms Done!
Time: 109
Avg:  92.13333333333334
{ users_cnt: 0,
  users_time: 0,
  rooms_cnt: 0,
  rooms_time: 0,
  bulk1_time: 0,
  interroom_time: 1,
  bulk2_time: 0,
  duration: 106.503423 }
TypeError: Cannot read property 'value' of null
    at db.localStorage.findOne.then.ret (/root/screeps-local/engine/runner/Core.js:324:23)
    at process._tickCallback (internal/process/next_tick.js:103:7)
`
This is what it spews to logs. This is without a user. When user exist, one tick takes 20 seconds.

**Comment by ags131** [comment]
It may be looking for gameTime, in a mongo shell, try 
`db.localStorage.insert({ key: 'gametime', value: 1 })`
If that fixes it then I'll add a check for it 
Usually when it takes 10-20 seconds, its timing out on user or room processing, I've been working on failing early in those cases and continuing, but it is still heavily WIP.

**Comment by Ondalf** [comment]
> Rooms Done!
> Time: 10111
> Avg:  104.8215027700831
> { users_cnt: 0,
>   users_time: 0,
>   rooms_cnt: 1,
>   rooms_time: 10007,
>   bulk1_time: 0,
>   interroom_time: 2,
>   bulk2_time: 0,
>   duration: 10104.231602 }
> TypeError: Cannot read property 'value' of null
>     at db.localStorage.findOne.then.ret (/root/screeps-local/engine/runner/Core.js:324:23)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> Rooms Done!
> Time: 10021
> Avg:  106.53799549939414
> { users_cnt: 0,
>   users_time: 0,
>   rooms_cnt: 1,
>   rooms_time: 9994,
>   bulk1_time: 0,
>   interroom_time: 2,
>   bulk2_time: 0,
>   duration: 10016.791294 }
> TypeError: Cannot read property 'value' of null
>     at db.localStorage.findOne.then.ret (/root/screeps-local/engine/runner/Core.js:324:23)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> 

Right after hitting enter after creating a room via API command. ^^^

> Rooms Done!
> Time: 10023
> Avg:  121.97372969236088
> { users_cnt: 0,
>   users_time: 0,
>   rooms_cnt: 1,
>   rooms_time: 9996,
>   bulk1_time: 0,
>   interroom_time: 4,
>   bulk2_time: 0,
>   duration: 10022.825741 }
> 

After the command for adding tick-counter. Seems one error has vanished, but can't say, its speedy yet. Good start though!
